version: '3.9'

services:
  node:
    build:
      context: .
      args:
        NODE_VERSION: 22.0.0
        ALPINE_VERSION: 3.19
    environment:
      RABBITMQ_HOST: amqp://user:passwd@rabbitmq:5672
    networks:
      - rabbitmq
    volumes:
      - ./:/app
    tty: true
    working_dir: /app
    depends_on:
      - rabbitmq

  rabbitmq:
    build:
      context: ./dockerfiles/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: passwd
    ports:
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmqdata: